[workspace]

members = [
  "mogwai",
  "crates/mogwai-html-macro",
  "crates/mogwai-hydrator",
  "examples/list-of-gizmos",
  "examples/sandbox",
  "examples/todomvc",
  "examples/multipage",
  "examples/spa-routing",
  "cookbook"
]


[profile.release]
lto = true
opt-level = 'z'
