name: "on push master"

on:
  push:
    branches: master

jobs:
  publish-cookbook-on-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-cookbook-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-cookbook-refs/heads/master
          ${{ runner.os }}-cargo-cookbook-
          ${{ runner.os }}-cargo-all-
    - name: test
      run: scripts/release_cookbook.sh
