name: "on tag"

on:
  push:
    tags: v*.*.*

jobs:
  publish-crates-on-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-all-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-all-refs/heads/master
          ${{ runner.os }}-cargo-all-

    - name: "publish crates to crates-io"
      run: scripts/release.sh ${{ secrets.cargo_token }}

  publish-cookbook-on-tag:
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-all-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-cookbook-refs/heads/master
          ${{ runner.os }}-cargo-cookbook-
          ${{ runner.os }}-cargo-all-

    - name: "publish cookbook to zyghost.com"
      run: scripts/release_cookbook.sh
